---
title: "Health and Economic Damages Caused by Storms in US"
author: "Kaung Myat Khant"
date: "`r Sys.Date()`"
output: 
  pdf_document:
      keep_md: TRUE

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

## Synopsis  

  
  
    
      
## Data processing      

**Due to the internet connection problem, I will not run some of the following lines to save the time rendering the pdf file.**

### Download and read the data
```{r downloads, include=T}
### URLs for download
docURL <- "https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf"
dataURL <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"

### download the files (but not run due to unstable internet connection)
# download.file(url = docURL, destfile = "data-documentation.pdf", method = "libcurl")
# download.file(url = dataURL, destfile = "storm-dataset.csv.bz2", method = "libcurl")

### read the data
data <- read.csv(bzfile("storm-dataset.csv.bz2"))
```

### Check the data
head(data)
  
  
    
    
      
      
      
## Results